### ISSUE TITLE
Manage settings from admin (django-constance)

### ISSUE THREAD

**Issue by nemesisdesign** [ninuxorg/nodeshot#147]
Some settings could be managed from the admin web interface using django-costance, to be done after #146 .

**Comment by nemesisdesign** [comment]
Probably unnecessary. Will reopen if really needed.

**Comment by vusy-nathan** [comment]
I have installed the nodeshot on ubuntu 14 server i can access the admin web interface. now i am stucked on how to add the nodes and see the their links on a map.
