### ISSUE TITLE
Flexible Add / Edit node

### ISSUE THREAD

**Issue by nemesisdesign** [ninuxorg/nodeshot#200]
The form for adding / editing nodes should be automatically generated with a solution like:
https://github.com/powmedia/backbone-forms

- [x] use backbone forms to edit node details
- [x] load node details according to backbone forms, including NODE_HSTORE_DATA
- [x] refactor add node to support configurable node fields

**Comment by vusy-nathan** [comment]
Hi nemesis i have installed nodeshot on ubuntu 14 server my next task is how to add the layers, nodes and view the links on a map. i have mesh network of seven nodes running batman-adv flashed on secn firmware based on openwrt. i will appreaciate  sample of layers addition of nodes.
