### ISSUE TITLE
A bug in social auth login was introduced in 4116e7d

### ISSUE THREAD

**Issue by d4nyl0** [ninuxorg/nodeshot#206]
This commit https://github.com/ninuxorg/nodeshot/commit/4116e7d291a28ae35ba68f856e6b1620a5b90269 introduced a problem in the social auth login feature, which does not have automatic tests because it depends from third parties sites like facebook or google.

After logging in the first time the user will get a 500 error because the system tries to create an email which already exists, moreover, the user will get a request to confirm his email address which is unnecessary because the social network already verifies the email address.

There should be a way to skip the automatic creation of EmailAddress objects in order to avoid this problem.

**Comment by nemesisdesign** [comment]
Do you mean on the ninux test instance?

**Comment by d4nyl0** [comment]
Yes.

**Comment by nemesisdesign** [comment]
One problem was specific to the settings of the ninux.org instance, after fixing that I discovered a bug introduced in this commit: https://github.com/ninuxorg/nodeshot/commit/4116e7d291a28ae35ba68f856e6b1620a5b90269

I'm going to rename the issue and update its description.

**Comment by d4nyl0** [comment]
Great, as you prefer.

Sorry for entropy generation. :-)

**Comment by nemesisdesign** [comment]
no need to be sorry, quite the opposite, keep sending feedback and bug reports
