### ISSUE TITLE
Bug in auth social login

### ISSUE THREAD

**Issue by d4nyl0** [ninuxorg/nodeshot#211]
I'm trying to login via Google+ OpenID authentication and I obtain a HTTP 500 server error.

Predecessor: https://github.com/ninuxorg/nodeshot/issues/206

**Comment by nemesisdesign** [comment]
Now should work, CLIENT_SECRET setting was wrong (my mistake). Try and let us know.

**Comment by d4nyl0** [comment]
Great! It works now.

Best wishes.
Danilo

**Comment by nemesisdesign** [comment]
:+1: thx for sending feedback
