### ISSUE TITLE
Generalization: change/modify "devices"

### ISSUE THREAD

**Issue by tubia** [ninuxorg/nodeshot#212]
Hi,
I'm trying to understand the degree of generalization of the software, to be used for other projects that imply georeference but are not related to networking devices. I see from the docs that it's possible to add/alter layers and categories inside the "nodes" but what seems to be fixed is the networking/hardware/devices content type (if I can call it in this way). Is there a way to configure/modify this type of content (I mean "devices").
Thank you for nodeshot, hope to see it in map.ninux.org soon :)

**Comment by nemesisdesign** [comment]
Hi @tubia,

you are right regarding the fact that the networking tools are quite not finished yet.

I will be refining all the django apps in `nodeshot.networking` during the next 3 months, when ready, the networking modules will probably be stored in a separate repository that will be focused on networking tools, I believe that makes more sense than keeping everything in one giant codebase, and It would be very useful if that could be used indipendently from postgis in the future.

But let's back to your case, when you write:

    I'm trying to understand the degree of generalization of the software, to be used for other projects that imply georeference but are not related to networking devices. 

Initially It seems to me that you don't need this feature. 

But later you ask if it is possible to configure it or modify it in some way, so I wonder, what exactly would you need to modify?

Federico

**Comment by nemesisdesign** [comment]
I'm closing this issue @tubia, if you have more questions or want to discuss other subjects reach us on the mailing list.
Thank you :+1:

**Comment by tubia** [comment]
Hi @nemesisdesign 
I lost the previous notification and ?ve been quite busy, sorry for not reply.  
To explain better, I would like to use Nodeshot for different kind of content, let's say POI (points of interest): for example I have a content type "ONG office" with certain fields associated and then "ONG hospital" with other fields. Is this possible?  
I'm joining the mailing-list :)

**Comment by nemesisdesign** [comment]
@tubia if ONG office and hospital have similar fields you can differentiate them with their status.
