### ISSUE TITLE
Configure account for admin console access?

### ISSUE THREAD

**Issue by Famicoman** [ninuxorg/nodeshot#275]
there a way to allow an account full access to the admin console without hitting postgres directly via:
```
update profiles_profile set is_staff = true where id = 1;
update profiles_profile set is_superuser = true where id = 1;
```

I can't find any mention in the documentation, and the ADMINS filed in settings.py doesn't seem to affect the admin console

**Comment by nemesisdesign** [comment]
You have to use the interface /admin/ by going to users and creating a new one (flag it as superuser and is_staff).

**Comment by Famicoman** [comment]
How do I log into the /admin/ interface if I don't already have a user flagged as is_staff?

**Comment by nemesisdesign** [comment]
the default superadmin is admin/admin as written in the docs:
http://docs.nodeshot.org/en/latest/topics/install_production_automated.html

Did you follow that procedure to install?

**Comment by Famicoman** [comment]
I used the manual production installation as the server already has running software that uses postgres, pyhon, and nginx. The warning on the automated production installation page made me hesitant about using it so I opted for the manual installation outlined here, http://docs.nodeshot.org/en/latest/topics/install_production_manual.html

It doesn't look like a default admin account was created via manual installation, so as far as I can tell the steps I took yielded the same results using the first account I created.

**Comment by nemesisdesign** [comment]
I think what you are experiencing is a bug. Unfortunately I haven't had time to maintain this software latelly.
